[package]
name = "odc_core"
version = "0.0.0"
edition = "2021"

[dependencies]
log = "0.4.14"
wgpu = "0.12.0"
raw-window-handle = "0.4.2"
pollster = "0.2.4"
bytemuck = "1.7.3"
glam = "0.20.2"

[dev-dependencies]
env_logger = "0.9.0"
winit = "0.26.0"
vp_cam = { path = "../vp_cam" }