[package]
name = "odc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
raw-window-handle = "0.4.2"

[dev-dependencies]
env_logger = "0.9.0"
winit = "0.26.0"
pollster = "0.2.4"